-- AlterTable
ALTER TABLE "AccumulationTerm" ALTER COLUMN "flowIn" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "flowOut" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "accumulationTerm" SET DATA TYPE DOUBLE PRECISION;
